In [5]:
%%html
<img src = "high.jpg">

<img src = "high.jpg">

# Linear Regression, Logistic Regression, Decision Tree

In [15]:
import pandas as pd
import matplotlib.pyplot as plt
df=pd.read_csv("emp.csv")
df.head()

Company        Job     Degree  Salary
0  Infosys      sales  Graduate   <50000
1  Infosys      sales  Post Grad  >50000
2  Infosys  Developer  Graduate   <50000
3  Infosys  Developer  Post Grad  >50000
4  Infosys    Manager  Graduate   <50000

In [16]:
x=df.drop('Salary',axis='columns')
y=df['Salary']

In [17]:
from sklearn.preprocessing import LabelEncoder
Company_1=LabelEncoder()
Job_1=LabelEncoder()
Degree_1=LabelEncoder()

In [18]:
x['Company_1']=Company_1.fit_transform(x['Company'])

In [19]:
x['Job_1']=Job_1.fit_transform(x['Job'])

In [20]:
x

Company        Job     Degree  Company_1  Job_1
0   Infosys      sales  Graduate           0      2
1   Infosys      sales  Post Grad          0      2
2   Infosys  Developer  Graduate           0      0
3   Infosys  Developer  Post Grad          0      0
4   Infosys    Manager  Graduate           0      1
5   Infosys    Manager  Post Grad          0      1
6     Wipro      sales  Graduate           2      2
7     Wipro      sales  Post Grad          2      2
8     Wipro  Developer  Graduate           2      0
9     Wipro  Developer  Post Grad          2      0
10    Wipro    Manager  Graduate           2      1
11    Wipro    Manager  Post Grad          2      1
12      TCS      sales  Graduate           1      2
13      TCS      sales  Post Grad          1      2
14      TCS  Developer  Graduate           1      0
15      TCS  Developer  Post Grad          1      0
16      TCS    Manager  Graduate           1      1
17      TCS    Manager  Post Grad          1      1

In [27]:
x['Degree_E']=Degree_1.fit_transform(x['Degree'])

In [38]:
x

(    Company        Job     Degree  Company_1  Job_1  Degree_E  Job_E
 0   Infosys      sales  Graduate           0      2         0      2
 1   Infosys      sales  Post Grad          0      2         1      2
 2   Infosys  Developer  Graduate           0      0         0      0
 3   Infosys  Developer  Post Grad          0      0         1      0
 4   Infosys    Manager  Graduate           0      1         0      1
 5   Infosys    Manager  Post Grad          0      1         1      1
 6     Wipro      sales  Graduate           2      2         0      2
 7     Wipro      sales  Post Grad          2      2         1      2
 8     Wipro  Developer  Graduate           2      0         0      0
 9     Wipro  Developer  Post Grad          2      0         1      0
 10    Wipro    Manager  Graduate           2      1         0      1
 11    Wipro    Manager  Post Grad          2      1         1      1
 12      TCS      sales  Graduate           1      2         0      2
 13      TCS      sa

In [39]:
y

0     <50000
1     >50000
2     <50000
3     >50000
4     <50000
5     >50000
6     <50000
7     >50000
8     <50000
9     >50000
10    <50000
11    >50000
12    <50000
13    >50000
14    <50000
15    >50000
16    <50000
17    >50000
Name: Salary, dtype: object

In [19]:
y.replace({'<50000':0,'>50000':1})

0     0
1     1
2     0
3     1
4     0
5     1
6     0
7     1
8     0
9     1
10    0
11    1
12    0
13    1
14    0
15    1
16    0
17    1
Name: Salary, dtype: int64

In [57]:
x1 = x.drop(['Company','Job','Degree',"Job_1"],axis='columns')

In [58]:
x1.head(5)

Company_1  Degree_E  Job_E
0          0         0      2
1          0         1      2
2          0         0      0
3          0         1      0
4          0         0      1

In [59]:
# ml model
from sklearn import tree
model=tree.DecisionTreeClassifier()

In [60]:
model.fit(x1,y)

DecisionTreeClassifier()

In [61]:
model.score(x1,y)

1.0

In [62]:
model.predict([[2,1,0]])

C:\Users\himanshu\AppData\Roaming\Python\Python311\site-packages\sklearn\base.py:465: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


array(['>50000'], dtype=object)

# act=2

In [21]:
df= pd.read_csv("dia.csv")
df.sample()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
113            4       76             62              0        0  34.0   

     DiabetesPedigreeFunction  Age  Outcome  
113                     0.391   25        0

In [22]:
x=df.drop('Outcome',axis='columns')
x.sample()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
302            5       77             82             41       42  35.8   

     DiabetesPedigreeFunction  Age  
302                     0.156   35

In [48]:
features_col=['Pregnancies',	'Glucose',	'BloodPressure',	'SkinThickness','BMI','DiabetesPedigreeFunction','Age']

In [26]:
y=df['Outcome']
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test= train_test_split(x,y)


In [27]:
x_train.shape

(576, 8)

In [28]:
x_test.shape

(192, 8)

In [29]:
576/768

0.75

In [30]:
# model
from sklearn.tree import DecisionTreeClassifier

In [31]:
model=DecisionTreeClassifier()

In [32]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [33]:
predicted_value=model.predict(x_test)

In [34]:
y_test


609    0
30     0
59     0
289    0
179    1
      ..
667    1
725    0
141    0
518    0
584    1
Name: Outcome, Length: 192, dtype: int64

In [35]:
model.score(x_test,y_test)

0.7135416666666666

In [36]:
model.score(x_train,y_train)

1.0

In [37]:
from sklearn import metrics

In [38]:
metrics.accuracy_score(y_test,predicted_value)

0.7135416666666666

In [39]:
pip install graphviz

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [40]:
pip install ipython

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [41]:
import pydotplus
from sklearn.tree import export_graphviz
from six import StringIO

In [42]:
pip install pydotplus

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [43]:
import Pillow as PIL

ModuleNotFoundError: No module named 'Pillow'

In [ ]:
pip install Pillow

In [44]:
from IPython.display import Image

In [45]:
a_data=StringIO()

In [53]:
export_graphviz(model,out_file=a_data,filled=True,rounded=True,feature_names=features_col)
graph=pydotplus.graph_fom_a_data(graph.write_png('blr.png'))
Image(graph.create_png())

ValueError: Length of feature_names, 7 does not match number of features, 8

In [50]:
pip install opencv-python

Defaulting to user installation because normal site-packages is not writeable
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/38.1 MB 119.1 kB/s eta 0:05:20
   ---------------------------------------- 0.0/38.1 MB 119.1 kB/s eta 0:05:20
   ---------------------------------------- 0.0/38.1 MB 115.5 kB/s eta 0:05:30
   ---------------------------------------- 0.0/38.1 MB 115.5 kB/s eta 0:05:30
   ---------------------------------------- 0.0/38.1 MB 115.5 kB/s eta 0:05:30
   ---------------------------------------- 0.1/38.1 MB 125.8 kB/s eta 0:05:03
   -------------------------

In [2]:
pip install Theano


Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np


In [7]:
pip install scipy

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [8]:
pip install pydot

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [10]:
 pip install Theano

Defaulting to user installation because normal site-packages is not writeable
Note: you may need to restart the kernel to use updated packages.


In [4]:
from theano import *

AttributeError: partially initialized module 'theano' has no attribute 'compile' (most likely due to a circular import)

In [5]:
pip install pymc3

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/872.2 kB ? eta -:--:--
     -- ------------------------------------ 61.4/872.2 kB 1.6 MB/s eta 0:00:01
     ---- --------------------------------- 112.6/872.2 kB 1.3 MB/s eta 0:00:01
     ----------- -------------------------- 256.0/872.2 kB 2.0 MB/s eta 0:00:01
     ----------------- -------------------- 409.6/872.2 kB 2.3 MB/s eta 0:00:01
     ------------------------ ------------- 563.2/872.2 kB 2.5 MB/s eta 0:00:01
     ------------------------------ ------- 706.6/872.2 kB 2.6 MB/s eta 0:00:01
     -------------------------------------  849.9/872.2 kB 2.7 MB/s eta 0:00:01
     -------------------------------------  870.4/872.2 kB 2.7 MB/s eta 0:00:01
     -------------------------------------- 872.2/872.2 kB 2.3 MB/s eta 0:00:00
     ---------------------------------------- 0.0/11.4 MB ? eta -:--:--
     ---------------------------------------- 0.0/11.4 MB

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [7]:
a_2=np.array([(2,54,657),(2,7,46)])

In [8]:
a_2

array([[  2,  54, 657],
       [  2,   7,  46]])

In [9]:
m=np.array([(22,54,65),(25,71,46)])
m

array([[22, 54, 65],
       [25, 71, 46]])

In [10]:
pip install tensor

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/50.3 kB ? eta -:--:--
     ------------------------------ ------- 41.0/50.3 kB 991.0 kB/s eta 0:00:01
     -------------------------------------- 50.3/50.3 kB 513.0 kB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
     ---------------------------------------- 0.0/296.5 kB ? eta -:--:--
     ------------------ ------------------- 143.4/296.5 kB 2.8 MB/s eta 0:00:01
     ------------------------------------ - 286.7/296.5 kB 2.9 MB/s eta 0:00:01
     -------------------------------------- 296.5/296.5 kB 2.0 MB/s eta 0:00:00
     ---------------------------------------- 0

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [18]:
pip install tensorflow

Defaulting to user installation because normal site-packages is not writeable
     ---------------------------------------- 0.0/57.5 kB ? eta -:--:--
     --------------------- ------------------ 30.7/57.5 kB 1.3 MB/s eta 0:00:01
     --------------------------------- ---- 51.2/57.5 kB 871.5 kB/s eta 0:00:01
     -------------------------------------- 57.5/57.5 kB 377.8 kB/s eta 0:00:00
     ---------------------------------------- 0.0/65.5 kB ? eta -:--:--
     ------ --------------------------------- 10.2/65.5 kB ? eta -:--:--
     ----------------- -------------------- 30.7/65.5 kB 660.6 kB/s eta 0:00:01
     ----------------------------------- -- 61.4/65.5 kB 544.7 kB/s eta 0:00:01
     -------------------------------------- 65.5/65.5 kB 391.8 kB/s eta 0:00:00
     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
     ---------------------------------------- 0.0/1.5 MB ? eta -:--:--
      --------------------------------------- 0.0/1.5 MB 435.7 kB/s eta 0:00:04
   

ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    unknown package:
        Expected sha256 51f96c729d61ff8e2e340df5b3b4db81a938258f1c9282ab09277896d0c408ae
             Got        c6ad3bacc011d9d8339e101225b4282d1e46135b3df29f0bfb76652de47bf8d6



In [23]:
import tensorflow
a=tensorflow.constant(m)
a

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[22, 54, 65],
       [25, 71, 46]])>

In [17]:
x=a_2*m
x

array([[   44,  2916, 42705],
       [   50,   497,  2116]])